# Generated by Django 5.1.5 on 2025-02-14 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_tags',
        ),
    ]
