# Generated by Django 5.1.5 on 2025-02-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_proof', models.FileField(upload_to='Assets/User/')),
                ('user_photo', models.FileField(upload_to='Assets/User/')),
                ('user_contact', models.CharField(max_length=50)),
                ('user_location', models.CharField(max_length=50)),
            ],
        ),
    ]
