# Generated by Django 5.1.5 on 2025-02-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_user',
            old_name='user_location',
            new_name='user_latitude',
        ),
        migrations.AddField(
            model_name='tbl_user',
            name='user_longitude',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
