# Generated by Django 5.1.5 on 2025-02-14 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_tool',
        ),
    ]
