# Generated by Django 5.1.5 on 2025-02-15 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_delete_tbl_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_file', models.FileField(upload_to='Assets/gallery/')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_tool')),
            ],
        ),
    ]
