# Generated by Django 5.1.5 on 2025-02-15 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
        ('User', '0008_tbl_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_title', models.CharField(max_length=50)),
                ('comp_content', models.CharField(max_length=50)),
                ('comp_reply', models.CharField(max_length=50)),
                ('comp_date', models.DateField(auto_now_add=True)),
                ('comp_status', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
