# Generated by Django 5.1.5 on 2025-02-16 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
        ('User', '0009_tbl_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_renttool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_tool_date', models.DateField(auto_now_add=True)),
                ('rent_tool_fromdate', models.DateField()),
                ('rent_tool_todate', models.DateField()),
                ('rent_tool_status', models.IntegerField(default=0)),
                ('rent_tool_price', models.CharField(max_length=50)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
