# Generated by Django 5.1.5 on 2025-03-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_tbl_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_renttool',
            name='rent_tool_qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tbl_tool',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
