# Generated by Django 5.1.5 on 2025-03-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_tbl_renttool_rent_tool_qty_tbl_tool_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_gallery',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='tbl_rating',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='tbl_rating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_renttool',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='tbl_renttool',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_tool',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_bookmark',
        ),
        migrations.DeleteModel(
            name='tbl_gallery',
        ),
        migrations.DeleteModel(
            name='tbl_rating',
        ),
        migrations.DeleteModel(
            name='tbl_renttool',
        ),
        migrations.DeleteModel(
            name='tbl_tool',
        ),
    ]
