# Generated by Django 5.1.5 on 2025-03-07 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_delete_tbl_district_delete_tbl_tags'),
        ('Guest', '0002_rename_user_location_tbl_user_user_latitude_and_more'),
        ('User', '0015_remove_tbl_gallery_tool_remove_tbl_rating_tool_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=50)),
                ('tool_details', models.CharField(max_length=50)),
                ('tool_priceperday', models.CharField(max_length=50)),
                ('tool_status', models.IntegerField(default=0)),
                ('qty', models.IntegerField(default=1)),
                ('gallery', models.FileField(upload_to='Assets/gallery/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_renttool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_tool_date', models.DateField(auto_now_add=True)),
                ('rent_tool_fromdate', models.DateField()),
                ('rent_tool_todate', models.DateField()),
                ('rent_tool_status', models.IntegerField(default=0)),
                ('rent_tool_price', models.CharField(max_length=50)),
                ('rent_tool_qty', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_tool')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_review', models.CharField(max_length=50)),
                ('rating_data', models.IntegerField()),
                ('rating_datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_tool')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_tool')),
            ],
        ),
    ]
