# Generated by Django 5.1.5 on 2025-03-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_alter_tbl_tool_gallery_tbl_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_tool',
            name='gallery',
        ),
    ]
