# Generated by Django 5.1.7 on 2025-03-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_tbl_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_payment',
            name='payment_date',
            field=models.DateField(null=True),
        ),
    ]
